name: terraform-destroy

on: workflow_dispatch

jobs:
    terraform-destroy-job:
            runs-on: ubuntu-latest
            steps:
               - name: terraform init command
                 run: terraform init
               - name: terraform destroy command
                 run: terraform destroy -auto-approve
               - name: github ctredentials
                 run: |
                    git config --global user.name "raavimanikanta"
                    git config --global user.email "raavimani123@gmail.com"
                    git add .
                    git commit -m "added state file"
                    git push
