# name: terraform-destroy

# on: 
#   workflow_dispatch

# jobs:
#     terraform-destroy-job :
#             name: 'Terraform Destroy'
#             runs-on: ubuntu-latest
#             steps:
#                - name: Get code 
#                  run: actions/checkout@v3
#                - name: hashicorp/setup-terraform@v1
#                - name: terraform init command
#                  run: terraform init
#                - name: terraform destroy command
#                  run: terraform destroy -auto-approve
#                - name: github credentials
#                  run: |
#                    git config --global user.name "raavimanikanta"
#                    git config --global user.email "raavimani123@gmail.com"
#                    git add .
#                    git commit -m "added state file"
#                    git push

name: Terraform Destroy

 

on:
  workflow_dispatch

 

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: terraform init 
        id: init
        run: terraform init -reconfigure 

      - name: Terraform destroy
        run: terraform destroy -auto-approve
