name: Terraform Destroy

on:
  workflow_dispatch

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_DEFAULT_REGION: us-east-1
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: terraform init 
        run: terraform init -reconfigure 
        working-directory: ./dashboards_using_for_each
        
      - name: Terraform destroy
        run: terraform destroy --auto-approve 
        working-directory: ./dashboards_using_for_each
