name: Terraform-apply

on: workflow_dispatch
env:
     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
     AWS_DEFAULT_REGION: us-east-1
     AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}


jobs:
   running_terraform_commands:
            name: 'Terraform'
            runs-on: ubuntu-latest
            steps:
                - name: Get code 
                  uses: actions/checkout@v3
                - name: Terraform init command 
                  run: terraform init 
                  working-directory: ./dashboards_using_for_each
                - name: Terraform plan command
                  run: terraform plan
                  working-directory: ./dashboards_using_for_each
                - name: Terraform apply command
                  run: terraform apply -auto-approve
                  working-directory: ./dashboards_using_for_each
             
