name: Terraform-apply

on: workflow_dispatch

jobs:
   running_terraform_commands:
            name: 'Terraform'
            runs-on: ubuntu-latest
            steps:
                - name: Get code 
                  uses: actions/checkout@v3
                - name: Terraform init command 
                  run: terraform init 
                - name: Terraform plan command
                  run: terraform plan
                - name: Terraform apply command
                  run: terraform apply -auto-approve
         
